### PR TITLE
Fix rescheduling and added features

### PR DESCRIPTION
**Pull request by eltonbor**
Hi, thanks for the great package that you made, it's being very useful.

I made some modifications but kept almost the same functionality.
The changes I made will be used by passing options to the config.

Returning the original document with the original sleepUntil is useful.
And not running the job when sleepUntil is null is what I first expected to happen when a new document is added.

The major change that I made is on the rescheduling, I was experiencing that some times the jobs were skipping some rescheduling.
On the eight test: `document should stop recurring at 'repeatUntil'` 
I changed the `t.is(repeated, 2);` from `2` to `3` because it was skipping the first rescheduling.

### CODE REVIEW

**Comment by xpepermint** [comment]
Hey @eltonbor. Sorry for my late reply. I will review your PR soon.

**Comment by xpepermint** [comment]
Hey @eltonbor! I'm struggling with this PR. Here are my thoughts:

**Fixed a bug that on getNextStart that skipped a reschedule**
Can we isolate that. This one looks interesting! Bugs are always the priority!

**Added more tests**
Always a good thing :).

**Added an option to save job statistics to a collection**
This should not be part of this library. It should be the responsability of the application logger.

**Added an option to pass the original document to onDocument**
**Added an option to not run the job for the first time if sleepUntil is null**
Please provide more information.

**Comment by xpepermint** [comment]
**Added an option to not run the job for the first time if sleepUntil is null**
I get your point here. This functionality has changed in `1.2.0`. Thanks for the proposal.

**Comment by eltonbor** [comment]
Hi thanks for reviewing,

The bug that I mention happened when reprocessDelay was zero, check around the line 183 of your code.
I think you tried to fix that by getting always the second re-scheduling but some times it was skipping one rescheduling.

My suggestion is doing this:

`
let next = dates[0];
if (this.config.reprocessDelay === 0 && future.isSame(next)) { // Avoid rescheduling to the same moment
when no reprocessDelay
   next = dates.length > 0 ? dates[1] : null;
}
`

``

**Comment by leonpanjtar** [comment]
@xpepermint please merge this one as it includes correct fixes for rescheduling.

**Comment by xpepermint** [comment]
Closing in favor of https://github.com/xpepermint/mongodb-cron/pull/6.

**Pull request closed without merging**
