### PR TITLE
Fixed snyk vulnerability

### PR DESCRIPTION
**Pull request by RajanDhinoja**
#19  Fixed.

@xpepermint @chdanielmueller can you take a look into it and merge it?

### CODE REVIEW

**Comment by xpepermint** [comment]
@RajanDhinoja Please make sure that the tests are passing ...

**Comment by RajanDhinoja** [comment]
@xpepermint  now tests are passing. npm audit is showing a few things so I have also fixed one vulnerability by npm audit fix.

**Comment by RajanDhinoja** [comment]
If it's fine with you then you can merge my changes. This will help to improve plugin health.

**Comment by xpepermint** [comment]
Thank you.

**Comment by RajanDhinoja** [comment]
@xpepermint Can we publish a new version that has my changes?

**Comment by xpepermint** [comment]
Done. I updated some other dependencies as well.

**Pull request merged**
